### ISSUE TITLE
feature ветки

### ISSUE THREAD

**Issue by sh-vasily** [mityamuch/Sale-of-railway-tickets#1]
@mityamuch Добрый день! Есть предложение по возможности код заливать не сразу в main, а сначала в отдельную ветку, а потом уже через Pull Request в main.  Это не сложно, но кажется всем так будет удобнее: я смогу сразу дать совет, а не ждать сдачи задания полностью. И отметить, например, что монга у вас полностью реализована

**Comment by mityamuch** [comment]
На текущий момент, я только создал репозиторий, и набросал примерную "архитектуру", в дальнейшем, будем пользоваться
